[tools]
aws = "2.28.23"
gradle = "8.14.3"
java = "temurin-25.0.0+36.0.LTS"
jj = "0.35.0"
jjui = "0.9.6"
koka = "3.2.2"
kotlin = "2.2.20"
python = "3.14.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]
